### ISSUE TITLE
Cannot change icons

### ISSUE THREAD

**Issue by alanzanattadev** [tuomashatakka/reduced-dark-ui#10]
Hi,

No matter what I set in Icons, they don't change :/

Thank you

**Comment by tuomashatakka** [comment]
Have you tried reloading the theme afterwards? It should help by now. I'm working on fixing it :)

**Comment by alanzanattadev** [comment]
I've noticed if I have the tree-view on the right it works but not on the left

**Comment by alanzanattadev** [comment]
Now I can change it when I have the old version of settings (the one where you have to write it manually), with the new UI I can't select icons, the UI is broken (I don't see icons, but weird unicode)

**Comment by tuomashatakka** [comment]
Hmm, the icon picker needs quite a bit of work. It's currently also really slow.

Sounds like the icon fonts are not loaded correctly, I'll take a look into this!

**Comment by tuomashatakka** [comment]
I guess the icon picker is ready enough now for this to be marked resolved 😔✌️
