### ISSUE TITLE
Close Tab Icon on the right instead of left

### ISSUE THREAD

**Issue by alanzanattadev** [tuomashatakka/reduced-dark-ui#12]
Hi,

Can you add a setting to let us choose if we want the close icon on the left or right for tabs ?

Thank you

**Comment by tuomashatakka** [comment]
I'll add that :) do you think it's better to allow the closing of inactive tab or would it be better if it should be activated before it could be closed? I've found myself closing tabs accidentally quite a few times. But maybe this'll help

**Comment by alanzanattadev** [comment]
Icon is too big, that's why we miss click on it :p

**Comment by tuomashatakka** [comment]
As of v0.7.1 icon position/visibility enum toggle is available under the theme settings view. It allows to switch the close button to the right edge of a tab or hide the close button completely.
