### ISSUE TITLE
Duplicated settings

### ISSUE THREAD

**Issue by alanzanattadev** [tuomashatakka/reduced-dark-ui#15]
Hi,

Some settings (specially the ones for fixed things) are duplicated, they are in the size and layout section, after the icons section, and in the readme section, but they only work in the size and layout section

Thank you

**Comment by tuomashatakka** [comment]
This is because the configSchema was restructured in the 0.4.0 update - running the ```reduced-dark-ui:reset-config``` should help!

**Comment by alanzanattadev** [comment]
I don't know if this is because of the other issue thrown, but it changes nothing

**Comment by tuomashatakka** [comment]
Weird. I'll take a closer look into this :)

**Comment by tuomashatakka** [comment]
Have you tried removing all theme's config keys from the atom's config file? It helped for me

**Comment by alanzanattadev** [comment]
it helped :) thank you
