### ISSUE TITLE
Width of project roots

### ISSUE THREAD

**Issue by alanzanattadev** [tuomashatakka/reduced-dark-ui#16]
Hi,

when we select the fixed project root setting, the project roots width is 100% of the tree-view width, whiwh is beautiful, but when we disable the fixed project root, it has a margin or padding, can you fix that ?

Thank you

**Comment by tuomashatakka** [comment]
This has been an issue I've meant to fix for ages 😀 it's just a matter of moving the padding and margin rules outside the "fixed project root" guard. I'll try to remember to fix this asap!

**Comment by alanzanattadev** [comment]
Haha, sometimes it does even with fixed one

**Comment by tuomashatakka** [comment]
I got this done!!!!! 

I'll probably cherry-pick it along with a couple of other disrputive issues during this eve:)

**Comment by tuomashatakka** [comment]
Now it's better. I noticed that there is still another margin or padding which causes a slight jump in the project directory list, I'll fix it now :)

**Comment by tuomashatakka** [comment]
I think this is good enough to get closed at its current state 🙋
