### ISSUE TITLE
Weird closing tab icon

### ISSUE THREAD

**Issue by alanzanattadev** [tuomashatakka/reduced-dark-ui#17]
![screenshot from 2017-01-20 22-07-52](https://cloud.githubusercontent.com/assets/9500204/22165600/f9dcff5a-df5c-11e6-9d21-4ecd7231139c.png)
Hi,

Why isn't an x icon for closing tab ?

Thank you

**Comment by tuomashatakka** [comment]
This is because it uses ionicons - this is fixed in the next patch! :)
