### ISSUE TITLE
Projects in inconsistent state

### ISSUE THREAD

**Issue by alanzanattadev** [tuomashatakka/reduced-dark-ui#19]
Hi,

With project root disabled, if I open the fourth project, and then the first one, the fourth one hide its files (leaving the project root but with the arrow as if it was opened). I can click two times on the fourth project root to reopen it, but if I click on a file, it hides again and doesn't handle the click, I have to close the first project root to be able to click on the fourth files.

Thank you :)

**Comment by tuomashatakka** [comment]
So now that the theme works with three project roots, the natural next step is four project roots 😯 (just trying to imply that I find it a bit funny that there is always the n+1:th case, even if I was sure that if it works with three roots, it will work with n roots). 

It may take a while for me to get into this. I have been doing some pretty heavy optimizations of which some have had really diverse  and unexpected effects. So it will take a while to finish the restructuring of the codebase. (but it has already solved at least a dozen of inconsistenices). 😃

**Comment by tuomashatakka** [comment]
This should be okay now. I had given the highest z-index for the selected project root - not the expanded one, so as soon as the focus was lost, other folders got a higher z. Now it should work with as many project roots as your display can display!
