### ISSUE TITLE
Fixed bar tar with vertically split

### ISSUE THREAD

**Issue by giardb** [tuomashatakka/reduced-dark-ui#22]
Hi,

Bug in the bar tabs, they collapse with horizontal split and vertical split (I have seen that you know that one) when used Fixed bar tar option. And if you want to try too with a vertically split and a horizontally split on the right panel, then try to use the fixed bar tar.

**Comment by tuomashatakka** [comment]
Hi and thanks for issuing this problem.

There are some issues with split panes when using fixed tab bar. I'm working on these problems, and actually the latest update should make the fixed tabs act a bit nicer. This has a high priority on my todo list.

**Comment by tuomashatakka** [comment]
I'll mark this closed now since the issue has been mostly resolved with a fallback to relative positioning. If you have any more issues or problems with the theme, please do raise a new issue :)
