### ISSUE TITLE
AWESOME

### ISSUE THREAD

**Issue by alanzanattadev** [tuomashatakka/reduced-dark-ui#26]
Hi,

I've retested reduced and I'm surprised how awesome it is :) Just an issue to say thank you ! It's not my daily theme :)

:)

**Comment by tuomashatakka** [comment]
Thanks, and good to see you're back 😛 Lots of optimization and fine-tuning ahead, but you got me realize this was about to turn into a feature creep so I made a decision to not inclune new features unless they are really kick ass 😛😛

**Comment by alanzanattadev** [comment]
My project http://molecule.sh is almost ready for a first alpha release, we're looking for feedback, would you be interested ? :)

**Comment by tuomashatakka** [comment]
@alanzanattadev I would gladly :) is it already on apm or do I need a key for that? I actually took a better look at molecule just now and it looks amazing!

**Comment by alanzanattadev** [comment]
@tuomashatakka let's contact me on alan.zanatta@outlook.com , to discuss about that :)
