### ISSUE TITLE
Tab alignment

### ISSUE THREAD

**Issue by alanzanattadev** [tuomashatakka/reduced-dark-ui#4]
Hi,

Please make tab alignment (left, center, right) selectable in settings :)

Thank you !

**Comment by tuomashatakka** [comment]
I will. I guess it could be bundled with the fixed tab width option as the fixed tab width will effectively override the alignment while active. 

Do you happen to have any ideas on how to solve the issue for the fixed tab bar with tab bars overlapping each others when there are multiple panes on a horizontal axis? (if you open a pane item in the right for example)

**Comment by tuomashatakka** [comment]
This was implemented in the commit fbe599da2721b32eb45a27877227e200fe19b2d7

I'll mark this closed :) If you have any suggestions for enhancing the functionality, feel free to reopen or submit a new issue :)
