### ISSUE TITLE
Background color selectable

### ISSUE THREAD

**Issue by alanzanattadev** [tuomashatakka/reduced-dark-ui#5]
Hi,

Make background color selectable (with an option to depend on the syntax color) :)

Thank you !

**Comment by tuomashatakka** [comment]
Hi

I will :) It is actually already on my todo!

I was trying to find out why the background had sometimes white lines here and there the other day, and to solve it, put all elements' background colors to transparent (except the main one). I found out that the ui looked great even with one background color.

**Comment by tuomashatakka** [comment]
There are some enhancements coming to the background color in the next update. Now practically every color is tinted :) I also switched the editor to be translucent so it blends in better.
