### ISSUE TITLE
Fixed projects roots overflowing on each others

### ISSUE THREAD

**Issue by alanzanattadev** [tuomashatakka/reduced-dark-ui#7]
Hi,

Let's imagine I have 4 project roots with fixed project root enabled, and I want to open the fourth, the 3 before will be after the selected one, hidding the first 10 files of the selected project

Thank you

**Comment by tuomashatakka** [comment]
Solution: expand the git folder, so the items that can't be seen are just the git folder's files :)) but seriously, I'll fix that. I guess I'll need to have multiple project roots into this theme's project so I remember to debug that more often.
