### ISSUE TITLE
Ugly settings background

### ISSUE THREAD

**Issue by alanzanattadev** [tuomashatakka/reduced-dark-ui#8]
Hi,

In settings pane, there's a wallpaper with icons which is ugly, can you remove it ? :D 
(sorry for all those issues, there's a lot haha)

Thank you

**Comment by tuomashatakka** [comment]
:D Yeah I guess I could, it's actually just the settings icon upscaled and with ~50% opacity. I don't use background images, they're too web 2.0-ish 😂

But yes, consider it gone, I don't like them either😄

**Comment by tuomashatakka** [comment]
The icons are now reverted, I'll take a look into the background color and sections when I have time!
